import { LineChart, Megaphone, ClipboardList, Search } from "lucide-react";

export const workers = [
  {
    id: "kainoa",
    name: "Kainoa",
    role: "Sales Outreach Agent",
    description: "Kainoa identifies qualified prospects, prepares personalized outreach, organizes follow-ups, and helps Zumify maintain a consistent sales pipeline.",
    status: "Active",
    currentTask: "Prepare personalized outreach for 5 qualified prospects.",
    completed: 3,
    lastRun: "Today, 10:31 AM",
    nextRun: "Tomorrow, 8:00 AM",
    schedule: "Weekdays — 8:00 AM",
    icon: LineChart,
    avatar: "/assets/KainoaProfile.jpg",
    bodyImage: "/assets/KainoaBody.png",
    color: "bg-emerald-50 text-emerald-700",
    borderColor: "border-emerald-200",
    theme: {
      bg: "bg-emerald-600 dark:bg-emerald-600",
      hover: "hover:bg-emerald-700",
      dot: "bg-emerald-600 dark:bg-emerald-500",
      pulse: "bg-emerald-500 shadow-[0_0_8px_rgba(16,185,129,0.8)]",
      panelBg: "bg-emerald-50 dark:bg-emerald-950/90",
      cardBg: "bg-emerald-100/50 dark:bg-emerald-900/40",
      cardBorder: "border-emerald-200 dark:border-emerald-800/60",
      containerBg: "bg-emerald-50 dark:bg-emerald-950",
      navBg: "bg-emerald-100/50 dark:bg-emerald-900/60 border-emerald-200 dark:border-emerald-800",
      navText: "text-emerald-950 dark:text-emerald-50",
      buttonSecondaryBg: "bg-white dark:bg-emerald-900/40 border-emerald-300 dark:border-emerald-700 hover:bg-emerald-50 dark:hover:bg-emerald-800 text-emerald-950 dark:text-emerald-50",
      textHeading: "text-emerald-950 dark:text-emerald-50",
      textBody: "text-emerald-900 dark:text-emerald-200",
      textMuted: "text-emerald-800 dark:text-emerald-300",
      iconBg: "bg-emerald-200 dark:bg-emerald-800 text-emerald-900 dark:text-emerald-100",
    },
    capabilities: [
      "Lead Qualification",
      "Prospect Research",
      "Email Drafting",
      "Follow-up Management"
    ]
  },
  {
    id: "maya",
    name: "Maya",
    role: "Marketing Agent",
    description: "Maya helps Zumify plan, research, and create marketing content across social media, website content, campaigns, and brand communications.",
    status: "Active",
    currentTask: "Generate this week's LinkedIn content ideas.",
    completed: 2,
    lastRun: "Today, 9:45 AM",
    nextRun: "Tomorrow, 9:00 AM",
    schedule: "Monday–Friday — 9:00 AM",
    icon: Megaphone,
    avatar: "/assets/MayaProfile.jpg",
    bodyImage: "/assets/MayaBody.png",
    color: "bg-pink-50 text-pink-700",
    borderColor: "border-pink-200",
    theme: {
      bg: "bg-pink-600 dark:bg-pink-600",
      hover: "hover:bg-pink-700",
      dot: "bg-pink-600 dark:bg-pink-500",
      pulse: "bg-pink-500 shadow-[0_0_8px_rgba(236,72,153,0.8)]",
      panelBg: "bg-pink-50 dark:bg-pink-950/90",
      cardBg: "bg-pink-100/50 dark:bg-pink-900/40",
      cardBorder: "border-pink-200 dark:border-pink-800/60",
      containerBg: "bg-pink-50 dark:bg-pink-950",
      navBg: "bg-pink-100/50 dark:bg-pink-900/60 border-pink-200 dark:border-pink-800",
      navText: "text-pink-950 dark:text-pink-50",
      buttonSecondaryBg: "bg-white dark:bg-pink-900/40 border-pink-300 dark:border-pink-700 hover:bg-pink-50 dark:hover:bg-pink-800 text-pink-950 dark:text-pink-50",
      textHeading: "text-pink-950 dark:text-pink-50",
      textBody: "text-pink-900 dark:text-pink-200",
      textMuted: "text-pink-800 dark:text-pink-300",
      iconBg: "bg-pink-200 dark:bg-pink-800 text-pink-900 dark:text-pink-100",
    },
    capabilities: [
      "Social Media Ideas",
      "Content Planning",
      "Marketing Research",
      "Campaign Ideas"
    ]
  },
  {
    id: "nora",
    name: "Nora",
    role: "Administration Agent",
    description: "Nora helps keep Zumify's internal operations organized by tracking administrative tasks, deadlines, documents, reminders, and recurring business operations.",
    status: "Active",
    currentTask: "Review upcoming administrative tasks.",
    completed: 4,
    lastRun: "Today, 9:00 AM",
    nextRun: "Monday, 8:00 AM",
    schedule: "Monday — 8:00 AM",
    icon: ClipboardList,
    avatar: "/assets/NoraProfile.jpg",
    bodyImage: "/assets/NoraBody.png",
    color: "bg-purple-50 text-purple-700",
    borderColor: "border-purple-200",
    theme: {
      bg: "bg-purple-600 dark:bg-purple-600",
      hover: "hover:bg-purple-700",
      dot: "bg-purple-600 dark:bg-purple-500",
      pulse: "bg-purple-500 shadow-[0_0_8px_rgba(168,85,247,0.8)]",
      panelBg: "bg-purple-50 dark:bg-purple-950/90",
      cardBg: "bg-purple-100/50 dark:bg-purple-900/40",
      cardBorder: "border-purple-200 dark:border-purple-800/60",
      containerBg: "bg-purple-50 dark:bg-purple-950",
      navBg: "bg-purple-100/50 dark:bg-purple-900/60 border-purple-200 dark:border-purple-800",
      navText: "text-purple-950 dark:text-purple-50",
      buttonSecondaryBg: "bg-white dark:bg-purple-900/40 border-purple-300 dark:border-purple-700 hover:bg-purple-50 dark:hover:bg-purple-800 text-purple-950 dark:text-purple-50",
      textHeading: "text-purple-950 dark:text-purple-50",
      textBody: "text-purple-900 dark:text-purple-200",
      textMuted: "text-purple-800 dark:text-purple-300",
      iconBg: "bg-purple-200 dark:bg-purple-800 text-purple-900 dark:text-purple-100",
    },
    capabilities: [
      "Administrative Reminders",
      "Task Organization",
      "Deadline Tracking",
      "Document Reminders"
    ]
  },
  {
    id: "kent",
    name: "Kent",
    role: "Research & Lead Intelligence Agent",
    description: "Kent researches businesses, industries, competitors, market opportunities, and potential Zumify prospects.",
    status: "Active",
    currentTask: "Find 10 Hawaii businesses that may need a website redesign.",
    completed: 5,
    lastRun: "Today, 10:42 AM",
    nextRun: "Tomorrow, 10:00 AM",
    schedule: "Weekdays — 10:00 AM",
    icon: Search,
    avatar: "/assets/KentProfile.jpg",
    bodyImage: "/assets/KentBody.png",
    color: "bg-blue-50 text-blue-700",
    borderColor: "border-blue-200",
    theme: {
      bg: "bg-blue-600 dark:bg-blue-600",
      hover: "hover:bg-blue-700",
      dot: "bg-blue-600 dark:bg-blue-500",
      pulse: "bg-blue-500 shadow-[0_0_8px_rgba(59,130,246,0.8)]",
      panelBg: "bg-blue-50 dark:bg-blue-950/90",
      cardBg: "bg-blue-100/50 dark:bg-blue-900/40",
      cardBorder: "border-blue-200 dark:border-blue-800/60",
      containerBg: "bg-blue-50 dark:bg-blue-950",
      navBg: "bg-blue-100/50 dark:bg-blue-900/60 border-blue-200 dark:border-blue-800",
      navText: "text-blue-950 dark:text-blue-50",
      buttonSecondaryBg: "bg-white dark:bg-blue-900/40 border-blue-300 dark:border-blue-700 hover:bg-blue-50 dark:hover:bg-blue-800 text-blue-950 dark:text-blue-50",
      textHeading: "text-blue-950 dark:text-blue-50",
      textBody: "text-blue-900 dark:text-blue-200",
      textMuted: "text-blue-800 dark:text-blue-300",
      iconBg: "bg-blue-200 dark:bg-blue-800 text-blue-900 dark:text-blue-100",
    },
    capabilities: [
      "Business Research",
      "Lead Discovery",
      "Competitor Research",
      "Market Research"
    ]
  },
];
